N = 5 # number of global iterations
L = 25 # construction steps per iteration
A = 6 # controls pheromone influence
B = 0.001 # controls heuristic influence
PHI = 0.005 # pheromone decay coefficient
T_init = 0.0001 # initial pheromone value
p = 0.1 # evaporation rate
mem = 10 # memory length in the ants
epsilon = 0.01 # difference between thresholds necessary for termination
C = 1.0 # contrast factor
Tp = 0.07